# FACEIT-setup-latest.exe /S
# Anti cheat: /VERYSILENT
# - name: install faceit AC
#   win_package: 
#     path: C:\FACEITInstaller_64.exe
#     arguments: "/VERYSILENT"

- name: install faceit client Stage
  win_package: 
    path: C:\FACEIT-setup-latest.exe
    arguments: "/S"
  vars: 
    ansible_user: Player
    ansible_password: Redbull9
  when: '"stageA" in group_names or "stageB" in group_names'

# - name: install faceit client A
#   win_package: 
#     path: C:\FACEIT-setup-latest.exe
#     arguments: "/S"
#   vars: 
#     ansible_user: groupA
#     ansible_password: Redbull5
#   when: '"groupsAC" in group_names or "tests" in group_names'

# - name: install faceit client C
#   win_package: 
#     path: C:\FACEIT-setup-latest.exe
#     arguments: "/S"
#   vars: 
#     ansible_user: groupC
#     ansible_password: Redbull7
#   when: '"groupsAC" in group_names or "tests" in group_names'

# - name: install faceit client B
#   win_package: 
#     path: C:\FACEIT-setup-latest.exe
#     arguments: "/S"
#   vars: 
#     ansible_user: groupB
#     ansible_password: Redbull6
#   when: '"groupsBD" in group_names or "tests" in group_names'

# - name: install faceit client D
#   win_package: 
#     path: C:\FACEIT-setup-latest.exe
#     arguments: "/S"
#   vars: 
#     ansible_user: groupD
#     ansible_password: Redbull8
#   when: '"groupsBD" in group_names or "tests" in group_names'
